[tool]
id = "graphql"

[[dependency]]
path = "../graphql-cli/build/libs/graphql-cli-@project.version@.jar"

[[dependency]]
path = "../graphql-code-generator/build/libs/graphql-code-generator-@project.version@.jar"

[[dependency]]
path = "../graphql-schema-file-generator/build/libs/graphql-schema-file-generator-@project.version@.jar"
